### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Gadgetoid** [Gadgetoid/rocks-and-diamonds-32blit#1]
- [x] dirt animation
- [x] falling diamonds
- [x] death!
- [ ] hold button to explode in exasperation if you get stuck
- [x] key actually unlocks door
- [ ] more levels!
- [x] sound and screen shake when things fall

For laughs: Exploding the player should blow away nearby dirt and knock a few rocks out of the level with appropriate velocity vectors.
